# Generated by Django 4.1.3 on 2022-12-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d/')),
                ('geo_locate', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('people_on_photo', models.TextField(blank=True)),
            ],
        ),
    ]
